# Generated by Django 4.1 on 2026-09-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre del taller')),
                ('tipo_taller', models.CharField(choices=[('arquitectura', 'Arquitectura'), ('escultura', 'Escultura'), ('pintura', 'Pintura'), ('musica', 'Música'), ('literatura', 'Literatura / Poesía'), ('danza', 'Danza'), ('teatro', 'Teatro'), ('cine', 'Cine / Audiovisual')], max_length=30, verbose_name='Área relacionada')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('duracion', models.PositiveSmallIntegerField(verbose_name='duración (horas)')),
                ('lugar', models.CharField(blank=True, max_length=254, null=True, verbose_name='Dirección del taller')),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor de entrada (si aplica)')),
                ('aforo_max', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aforo máximo')),
                ('fk_tallerista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariotallerista', to_field='email', verbose_name='email tallerista (VERIFICA)')),
            ],
        ),
        migrations.CreateModel(
            name='usuario_por_taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Escuela.taller')),
                ('fk_UsuarioBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariobase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usuario_por_taller',
            constraint=models.UniqueConstraint(fields=('fk_UsuarioBase', 'fk_Taller'), name='unique_usuario_taller'),
        ),
    ]
