# Generated by Django 4.1 on 2026-09-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre completo')),
                ('nick_name', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('fav_art', models.CharField(choices=[('arquitectura', 'Arquitectura'), ('escultura', 'Escultura'), ('pintura', 'Pintura'), ('musica', 'Música'), ('literatura', 'Literatura / Poesía'), ('danza', 'Danza'), ('teatro', 'Teatro'), ('cine', 'Cine / Audiovisual')], max_length=30, verbose_name='Arte favorito')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('organization', models.CharField(blank=True, max_length=254, null=True, verbose_name='Organización (si aplica)')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad de residencia')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTallerista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('nick_name', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('password', models.CharField(default='', max_length=128, verbose_name='Contraseña')),
                ('profession', models.CharField(choices=[('arquitectura', 'Arquitectura'), ('escultura', 'Escultura'), ('pintura', 'Pintura'), ('musica', 'Música'), ('literatura', 'Literatura / Poesía'), ('danza', 'Danza'), ('teatro', 'Teatro'), ('cine', 'Cine / Audiovisual')], max_length=60, verbose_name='Rubro/Profesión')),
                ('years_experience', models.PositiveSmallIntegerField(verbose_name='Años de experiencia')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad de residencia')),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
