# Generated by Django 4.1 on 2026-09-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=254, verbose_name='Nombre del artículo')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('categoria', models.CharField(choices=[('artesanias', 'Artesanías'), ('literatura', 'Literatura'), ('vestuario', 'Vestuario'), ('audiovisual', 'Audiovisuales'), ('fotografia', 'Fotografía'), ('patrimonio', 'Patrimonio y cultura'), ('alimentos', 'Bebidas/Alimentación'), ('otros', 'Otros')], max_length=25, verbose_name='Categoría')),
                ('imagen', models.ImageField(upload_to='Productos/')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad de origen')),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariobase', to_field='email', verbose_name='email (VERIFICA)')),
            ],
        ),
    ]
