# Generated by Django 4.1 on 2026-09-18 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Posts/', verbose_name='Imágen')),
                ('video', models.FileField(blank=True, null=True, upload_to='Posts/', verbose_name='Video')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Estado (default: activo)')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariobase', to_field='nick_name', verbose_name='Autor/a del post')),
            ],
        ),
        migrations.CreateModel(
            name='ObraLiteraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, max_length=254, verbose_name='Título de la obra')),
                ('corriente', models.CharField(choices=[('aventura', 'Aventura'), ('autobiografia', 'Autobiografía'), ('biografia', 'Biografía'), ('ciencia_ficcion', 'Ciencia ficción'), ('cuento', 'Cuento'), ('cronica', 'Crónica'), ('distopia', 'Distopía'), ('ensayo', 'Ensayo'), ('eutherpoiesis', 'Eutherpoiésis'), ('experimental', 'Literatura experimental'), ('literatura_infantil', 'Literatura infantil'), ('literatura_juvenil', 'Literatura juvenil'), ('fantasia', 'Fantasía'), ('folclor', 'Folclor'), ('historica', 'Novela histórica'), ('humor', 'Humor'), ('mitologia', 'Mitología'), ('misterio', 'Misterio/Suspenso'), ('novela', 'Novela'), ('poesia', 'Poesía'), ('realismo_magico', 'Realismo mágico'), ('romance', 'Romance'), ('satira', 'Sátira'), ('teatro', 'Teatro'), ('terror', 'Terror')], max_length=30, verbose_name='Género literario')),
                ('sinopsis', models.CharField(max_length=254, verbose_name='Sinópsis')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuariobase', to_field='nick_name', verbose_name='Autor/a de la obra')),
            ],
        ),
    ]
